version: '2.2'

services:

  php:
    build: ./php7
    image: bitrix/php7
    working_dir: /var/www
    volumes_from:
      - source
    links:
      - mysql
      - memcached
    restart: always

  nginx:
    build: ./nginx
    image: bitrix/nginx
    restart: always
    depends_on:
      - source
    volumes_from:
      - source
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    links:
      - php


  mysql:
    image: mysql:5.7
    volumes_from:
      - source
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysqld --sql-mode=""
    restart: always

  memcached:
    image: memcached:alpine
    restart: always
    volumes_from:
      - source

  source:
    image: alpine:latest
    restart: always
    volumes:
    #nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/sites-available:/etc/nginx/sites-available/

    #mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    #php
      - ./php7/php.ini:/etc/php/7.1/fpm/conf.d/90-php.ini
      - ./php7/php.ini:/etc/php/7.1/cli/conf.d/90-php.ini

    #logs
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php
      - ./logs/mysql:/var/log/mysql
      - ./logs/memcached:/var/log/memcached

      - ./data/mysql:/var/lib/mysql
      - ./data/memcached:/var/lib/memcached

      - ./www/:/var/www/sites

      - /etc/localtime:/etc/localtime/:ro