version: '2.2'

services:

  #PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}_pm"
    networks:
      - proxy_nw
    #environment: # если нужно подключаться к другим серверам
    #- PMA_ARBITRARY=1
    environment:
      - VIRTUAL_HOST=pm.${HTTP_HOST}
    links:
      - mysql:db
    restart: unless-stopped

  #NodeJs
#  node:
#    build: ./node
#    image: pramana/node
#   restart: unless-stopped
#    tty: true
#    working_dir: /var/www
#    volumes_from:
#      - source

  php:
    build: ./php7
    image: bitrix/php7
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    networks:
      - proxy_nw
    working_dir: /var/www
    volumes_from:
      - source
    links:
      - mysql
      - memcached
    restart: unless-stopped

  nginx:
    build: ./nginx
    image: bitrix/nginx
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    networks:
      - proxy_nw
    restart: unless-stopped
    depends_on:
      - source
    volumes_from:
      - source
    environment:
      - VIRTUAL_HOST=${HTTP_HOST}
    links:
      - php
    #command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mysql:
    image: mysql:5.7
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    networks:
      - proxy_nw
    volumes_from:
      - source
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
#   command: "chmod 0644 /etc/mysql/conf.d/my.cnf && mysqld --sql-mode=''"
    command: mysqld --sql-mode=""
    restart: unless-stopped

  memcached:
    image: memcached:alpine
    container_name: "${COMPOSE_PROJECT_NAME}_memcached"
    networks:
      - proxy_nw
    restart: unless-stopped
    volumes_from:
      - source

  source:
    image: alpine:latest
    container_name: "${COMPOSE_PROJECT_NAME}_source"
    networks:
      - proxy_nw
    restart: unless-stopped
    volumes:
    #nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/sites-available:/etc/nginx/sites-available/

    #mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/my.cnf:/etc/my.cnf

    #php
      - ./php7/php.ini:/etc/php/7.1/fpm/conf.d/90-php.ini
      - ./php7/php.ini:/etc/php/7.1/cli/conf.d/90-php.ini

    #logs
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php
      - ./logs/mysql:/var/log/mysql
      - ./logs/memcached:/var/log/memcached

      - ./data/mysql:/var/lib/mysql
      - ./data/memcached:/var/lib/memcached

      - ./www/:/var/www/sites

      - /etc/localtime:/etc/localtime/:ro

networks:
  proxy_nw:
    external: true